# Generated by Django 4.2.10 on 2024-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soma', '0003_remove_member_book_remove_member_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cost_incurred',
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='borrowed_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='date_returned',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
