# Generated by Django 4.2.10 on 2024-03-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soma', '0004_remove_member_cost_incurred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='borrowed_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
