# Generated by Django 4.2.10 on 2024-03-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soma', '0006_alter_book_cost_alter_booktransaction_date_borrowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='date_borrowed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='date_returned',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
